// import "./globals.css";
// import styles from "./page.module.scss";
import './page.css'

// import NavbarTwo from "../components/navbarTwo";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Golden Rule Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoWhite.png" />
      </head>
      <body>
      {/* <NavbarTwo /> */}
        {children}
        </body>
    </html>
  );
}
